cities = {
    0: 'Aracaju',
    1: 'Belém',
    2: 'Belo Horizonte',
    3: 'Boa Vista',
    4: 'Brasília',
    5: 'Campo Grande',
    6: 'Cuiabá',
    7: 'Curitiba',
    8: 'Florianópolis',
    9: 'Fortaleza',
    10: 'Goiânia',
    11: 'João Pessoa',
    12: 'Macapá',
    13: 'Maceió',
    14: 'Manaus',
    15: 'Natal',
    16: 'Palmas',
    17: 'Porto Alegre',
    18: 'Porto Velho',
    19: 'Recife',
    20: 'Rio Branco',
    21: 'Rio de Janeiro',
    22: 'Salvador',
    23: 'São Luís',
    24: 'São Paulo',
    25: 'Teresina',
    26: 'Vitória'
}